name: CI and CD application for building and deploying app

on:
  push:
    branches:
      - main

jobs:

  # CI Job
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Create the Node.js application
        run: echo "This is the testing code" > app.js

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.js


  # CD Job
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Download application artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: application

      - name: Check downloaded application
        run: cat application/app.js

      - name: Deploy application
        run: echo "Deploying application..."

